#!/bin/bash

set -e

cd "$(dirname "$0")/../builtinFonts"

echo "// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh"
echo "#pragma once"
echo ""

echo "#define LITERATAMONO_10_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./literatamono_10_regular.h",
  "./literatamono_10_bold.h",
  "./literatamono_10_bolditalic.h",
  "./literatamono_10_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define LITERATAMONO_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./literatamono_12_regular.h",
  "./literatamono_12_bold.h",
  "./literatamono_12_bolditalic.h",
  "./literatamono_12_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define LITERATAMONO_14_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./literatamono_14_regular.h",
  "./literatamono_14_bold.h",
  "./literatamono_14_bolditalic.h",
  "./literatamono_14_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define LITERATAMONO_16_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./literatamono_16_regular.h",
  "./literatamono_16_bold.h",
  "./literatamono_16_bolditalic.h",
  "./literatamono_16_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define LITERATAMONO_18_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./literatamono_18_regular.h",
  "./literatamono_18_bold.h",
  "./literatamono_18_bolditalic.h",
  "./literatamono_18_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define NOTOSANS_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notosans_12_regular.h",
  "./notosans_12_bold.h",
  "./notosans_12_bolditalic.h",
  "./notosans_12_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define NOTOSANS_14_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notosans_14_regular.h",
  "./notosans_14_bold.h",
  "./notosans_14_bolditalic.h",
  "./notosans_14_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define NOTOSANS_16_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notosans_16_regular.h",
  "./notosans_16_bold.h",
  "./notosans_16_bolditalic.h",
  "./notosans_16_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define NOTOSANS_18_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notosans_18_regular.h",
  "./notosans_18_bold.h",
  "./notosans_18_bolditalic.h",
  "./notosans_18_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UI_10_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./ubuntu_10_regular.h",
  "./ubuntu_10_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UI_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./ubuntu_12_regular.h",
  "./ubuntu_12_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define SMALL_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notosans_8_regular.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

FONT_ID_NAMES=(
  LITERATAMONO_10_FONT_ID
  LITERATAMONO_12_FONT_ID
  LITERATAMONO_14_FONT_ID
  LITERATAMONO_16_FONT_ID
  LITERATAMONO_18_FONT_ID
  NOTOSANS_12_FONT_ID
  NOTOSANS_14_FONT_ID
  NOTOSANS_16_FONT_ID
  NOTOSANS_18_FONT_ID
  UI_10_FONT_ID
  UI_12_FONT_ID
  SMALL_FONT_ID
)

echo ""
echo "// Font ID 0 is reserved as the \"not found\" sentinel."
echo "// Guard against any hash accidentally producing 0."
for name in "${FONT_ID_NAMES[@]}"; do
  echo "static_assert(${name} != 0, \"Font ID collision with sentinel\");"
done
