#pragma once

#include <builtinFonts/literatamono_10_bold.h>
#include <builtinFonts/literatamono_10_bolditalic.h>
#include <builtinFonts/literatamono_10_italic.h>
#include <builtinFonts/literatamono_10_regular.h>
#include <builtinFonts/literatamono_12_bold.h>
#include <builtinFonts/literatamono_12_bolditalic.h>
#include <builtinFonts/literatamono_12_italic.h>
#include <builtinFonts/literatamono_12_regular.h>
#include <builtinFonts/literatamono_14_bold.h>
#include <builtinFonts/literatamono_14_bolditalic.h>
#include <builtinFonts/literatamono_14_italic.h>
#include <builtinFonts/literatamono_14_regular.h>
#include <builtinFonts/literatamono_16_bold.h>
#include <builtinFonts/literatamono_16_bolditalic.h>
#include <builtinFonts/literatamono_16_italic.h>
#include <builtinFonts/literatamono_16_regular.h>
#include <builtinFonts/literatamono_18_bold.h>
#include <builtinFonts/literatamono_18_bolditalic.h>
#include <builtinFonts/literatamono_18_italic.h>
#include <builtinFonts/literatamono_18_regular.h>
#include <builtinFonts/notosans_8_regular.h>
#include <builtinFonts/notosans_12_bold.h>
#include <builtinFonts/notosans_12_bolditalic.h>
#include <builtinFonts/notosans_12_italic.h>
#include <builtinFonts/notosans_12_regular.h>
#include <builtinFonts/notosans_14_bold.h>
#include <builtinFonts/notosans_14_bolditalic.h>
#include <builtinFonts/notosans_14_italic.h>
#include <builtinFonts/notosans_14_regular.h>
#include <builtinFonts/notosans_16_bold.h>
#include <builtinFonts/notosans_16_bolditalic.h>
#include <builtinFonts/notosans_16_italic.h>
#include <builtinFonts/notosans_16_regular.h>
#include <builtinFonts/notosans_18_bold.h>
#include <builtinFonts/notosans_18_bolditalic.h>
#include <builtinFonts/notosans_18_italic.h>
#include <builtinFonts/notosans_18_regular.h>
#include <builtinFonts/ubuntu_10_bold.h>
#include <builtinFonts/ubuntu_10_regular.h>
#include <builtinFonts/ubuntu_12_bold.h>
#include <builtinFonts/ubuntu_12_regular.h>
