// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define LITERATAMONO_10_FONT_ID (1334565496)
#define LITERATAMONO_12_FONT_ID (-290061909)
#define LITERATAMONO_14_FONT_ID (766147836)
#define LITERATAMONO_16_FONT_ID (-1625718118)
#define LITERATAMONO_18_FONT_ID (-460625153)
#define NOTOSANS_10_FONT_ID (-1519978508)
#define NOTOSANS_12_FONT_ID (-781510085)
#define NOTOSANS_14_FONT_ID (-2071660262)
#define NOTOSANS_16_FONT_ID (-1874372285)
#define NOTOSANS_18_FONT_ID (1822714524)
#define UI_10_FONT_ID (1322569422)
#define UI_12_FONT_ID (1831230762)
#define SMALL_FONT_ID (1465627787)

// Font ID 0 is reserved as the "not found" sentinel.
// Guard against any hash accidentally producing 0.
static_assert(LITERATAMONO_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LITERATAMONO_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LITERATAMONO_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LITERATAMONO_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LITERATAMONO_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
